[workspace]
authors = ["Hamish Steptoe <hamish.steptoe@metoffice.gov.uk>"]
channels = ["conda-forge"]
name = "exeter-cycle-campaign"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
r = ">=4.4,<4.5"
numpy = ">=2.3.2,<3"
matplotlib = ">=3.10.3,<4"
pymc = ">=5.25.1,<6"
numpyro = ">=0.18.0,<0.19"
pip = ">=25.1.1,<26"
ipykernel = ">=6.29.5,<7"
pytensor = ">=2.31.7,<3"
libopenblas = ">=0.3.30,<0.4"
blas = ">=2.132,<3"
arviz = ">=0.22.0,<0.23"
ipywidgets = ">=8.1.7,<9"
seaborn = ">=0.13.2,<0.14"
